function acknowledgement
% F=mfilename('fullpath');
% p=fileparts(F);
% 
% [im, map] = imread([p filesep 'postcard.gif']);
%disp(' ')
%disp(' ')
%txt = {'Please acknowlegde SpliLab by citing our article:',...
%' ',....
%'Wuestefeld, A.; Bokelmann, G.H.R.; Zaroli, C.; Barruol, G.',...
%'Splitlab - A Shear wave splitting environment in MatLab',...
%'Computers and Geosciences, 2008; Vol.34(5), 515-528',...
%'<a href="matlab:web(''http://dx.doi.org/10.1016/j.cageo.2007.08.002'' , ''-browser'')">DOI: 10.1016/j.cageo.2007.08.002</a> ',...
%' ',' '};
%h=msgbox(txt(1:5),'Acknowlegdement','help','modal');
%disp(char(txt))

%waitfor(h)
