function viewphases
global config thiseq

mpos =get(0,'PointerLocation');
figpos = [mpos(1)-50 mpos(2)-370 200 380];

selPha = findobj('type','figure', 'tag','SelectPhase');
if ~isempty(selPha)
    uistack(selPha, 'top');
    return
end

figure('Position',figpos,...
           'NumberTitle','off',...
           'Name','Select Phase',...
           'Tag', 'SelectPhase',...
           'Toolbar','None',...
           'menubar','none');
       
Plist={'P','S','Pdiff','Sdiff','PP','SS','PPP','PcP','PcS','ScS','ScP','PS','SP',...
    'SKP','PKS','SKS','SKiKS','sSKS','pSKS', ...
    'pP', 'sP', 'pS', 'sS','PKKP', 'PKKS','SKKS', 'SKKP'}; % Phase data
[truefalse, index] = ismember('SKS', Plist);               % get index of default phase
models = unique([config.earthmodel, {'PREM','IASP91','AK135'}],'stable');


%% BUTTONS
button = uicontrol('Units','pixel',...
                   'Style','Pushbutton',...
                   'Position',[90 325 100 20],...
                   'Tag', config.earthmodel,...
                   'String', 'View travel times',...
                   'Callback',['model=get(gcbo,''Tag'');',...
                               'phases=get(gcbo,''UserData'');',... 
                               'SL_ttcurves(model, phases, thiseq.depth, thiseq.dis, config.eqwin);',...
                               'clear model phases;',... 
                               'close(gcbf)']);

uicontrol('Units','pixel',...
    'Style','PopupMenu',...
    'BackgroundColor','w',...
    'Position',[90 295 100 20],...
    'String',  models,...
    'Userdata', button,...
    'CallBack',['tmp1=get(gcbo,''Value'');',... 
                'tmp2=lower(get(gcbo,''String''));',... 
                'tmp3=get(gcbo,''UserData'');',... 
                'tmp=char(tmp2(tmp1));',... 
                'disp(tmp);',... 
                'set(tmp3, ''Tag'',tmp);',... 
                'clear tmp*']);

uicontrol('Units','pixel',...
    'Style','List',...
    'Min',1,...
    'Max',20,...
    'BackgroundColor','w',...
    'Userdata',button,...
    'Position',[15 15 70 figpos(4)-50],...
    'Value',index,...
    'String', Plist,...
    'Callback', ['tmp1=get(gcbo,''Value'');',... 
                 'tmp2=get(gcbo,''String'');',...
                 'tmpHandle=get(gcbo,''UserData'');',...
                 'set(tmpHandle, ''Userdata'', tmp2(tmp1));',...
                 'clear tmp* ']);
 
set(button, 'Userdata', Plist(index));          % to set directly default phase
set(button, 'Tag', char(lower(models(1))));     % to set directly default model
